import { CalendarDays, CheckCircle2, Circle, ClipboardCheck, Clock3, ListFilter, LogOut, Plus, Settings2, Trash2, UserRound, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { CalendarBoard } from "@/components/CalendarBoard";
import { PomodoroPanel } from "@/components/PomodoroPanel";
import { trpc } from "@/lib/trpc";

type StudentUser = { id: number; name: string; email: string | null; role: "staff" | "student"; createdAt: Date; updatedAt: Date };
type Priority = "low" | "medium" | "high";
type PersonalDraft = { subject: string; title: string; description: string; dueDate: string; priority: Priority };
const blankPersonal = (): PersonalDraft => ({ subject: "", title: "", description: "", dueDate: "", priority: "medium" });
const dayStart = (date: Date) => new Date(date.getFullYear(), date.getMonth(), date.getDate()).getTime();
const dueState = (date: Date, done = false) => { if (done) return "complete"; const days = Math.ceil((dayStart(date) - dayStart(new Date())) / 86_400_000); if (days < 0) return "overdue"; if (days <= 3) return "soon"; return "open"; };
const dueText = (date: Date) => { const days = Math.ceil((dayStart(date) - dayStart(new Date())) / 86_400_000); if (days < 0) return `${Math.abs(days)}d overdue`; if (days === 0) return "Due today"; if (days === 1) return "Due tomorrow"; return `Due ${new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric" }).format(date)}`; };
const dateInputValue = (value: Date) => new Date(value.getTime() - value.getTimezoneOffset() * 60_000).toISOString().slice(0, 10);
const priorityRank: Record<Priority, number> = { high: 0, medium: 1, low: 2 };

export default function StudentTerminal({ user }: { user: StudentUser }) {
  const utils = trpc.useUtils();
  const { data: assigned = [], isLoading: assignedLoading } = trpc.student.assigned.useQuery(undefined);
  const { data: personal = [] } = trpc.student.personal.useQuery(undefined);
  const { data: preferences } = trpc.student.preferences.useQuery(undefined);
  const [tab, setTab] = useState<"assigned" | "personal" | "calendar" | "settings">("assigned");
  const [sortBy, setSortBy] = useState<"due" | "priority">("due");
  const [showComposer, setShowComposer] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [draft, setDraft] = useState<PersonalDraft>(blankPersonal());
  const [preferenceDraft, setPreferenceDraft] = useState({ reminderOptIn: true, reminderLeadHours: 24, focusMinutes: 25, shortBreakMinutes: 5, longBreakMinutes: 15 });
  useEffect(() => { if (preferences) setPreferenceDraft({ reminderOptIn: preferences.reminderOptIn, reminderLeadHours: preferences.reminderLeadHours, focusMinutes: preferences.focusMinutes, shortBreakMinutes: preferences.shortBreakMinutes, longBreakMinutes: preferences.longBreakMinutes }); }, [preferences]);
  const setAssignedStatus = trpc.student.setAssignedStatus.useMutation({ onSuccess: () => utils.student.assigned.invalidate() });
  const setPersonalStatus = trpc.student.setPersonalStatus.useMutation({ onSuccess: () => utils.student.personal.invalidate() });
  const createPersonal = trpc.student.createPersonal.useMutation({ onSuccess: () => { utils.student.personal.invalidate(); toast.success("Personal task added."); closeComposer(); } });
  const updatePersonal = trpc.student.updatePersonal.useMutation({ onSuccess: () => { utils.student.personal.invalidate(); toast.success("Personal task updated."); closeComposer(); } });
  const deletePersonal = trpc.student.deletePersonal.useMutation({ onSuccess: () => { utils.student.personal.invalidate(); toast.success("Personal task deleted."); } });
  const updatePreferences = trpc.student.updatePreferences.useMutation({ onSuccess: () => { utils.student.preferences.invalidate(); toast.success("Settings saved."); } });
  const logout = trpc.auth.logout.useMutation({ onSuccess: () => utils.auth.me.invalidate() });
  const assignedStats = useMemo(() => ({ complete: assigned.filter(item => item.done).length, open: assigned.filter(item => !item.done).length, overdue: assigned.filter(item => dueState(new Date(item.dueDate), item.done) === "overdue").length }), [assigned]);
  const sortedAssigned = useMemo(() => [...assigned].sort((a, b) => sortBy === "priority" ? priorityRank[a.priority] - priorityRank[b.priority] || new Date(a.dueDate).getTime() - new Date(b.dueDate).getTime() : new Date(a.dueDate).getTime() - new Date(b.dueDate).getTime()), [assigned, sortBy]);
  const sortedPersonal = useMemo(() => [...personal].sort((a, b) => sortBy === "priority" ? priorityRank[a.priority] - priorityRank[b.priority] || new Date(a.dueDate).getTime() - new Date(b.dueDate).getTime() : new Date(a.dueDate).getTime() - new Date(b.dueDate).getTime()), [personal, sortBy]);

  function closeComposer() { setShowComposer(false); setEditingId(null); setDraft(blankPersonal()); }
  function editPersonal(item: typeof personal[number]) { setTab("personal"); setEditingId(item.id); setDraft({ subject: item.subject, title: item.title, description: item.description ?? "", dueDate: dateInputValue(new Date(item.dueDate)), priority: item.priority }); setShowComposer(true); }
  async function savePersonal(event: React.FormEvent) { event.preventDefault(); const assignment = { ...draft, description: draft.description || null, dueDate: new Date(`${draft.dueDate}T12:00:00`).getTime() }; try { if (editingId) await updatePersonal.mutateAsync({ id: editingId, assignment }); else await createPersonal.mutateAsync(assignment); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not save personal task."); } }
  async function savePreferences() { try { await updatePreferences.mutateAsync(preferenceDraft); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not save settings."); } }

  const calendarItems = [...assigned, ...personal].map(item => ({ id: item.id + ("studentId" in item ? 1000000 : 0), title: item.title, subject: item.subject, dueDate: item.dueDate, priority: item.priority, done: item.done }));
  return <div className="student-shell"><header className="student-topbar"><div className="brand-lockup"><span className="brand-mark">N</span><div><strong>NEON</strong><small>PERSONAL TERMINAL</small></div></div><div className="student-profile"><span><UserRound size={15} />{user.name}</span><button onClick={() => logout.mutate()} aria-label="Log out"><LogOut size={16} /></button></div></header><main className="student-main"><section className="student-intro"><div><p className="eyebrow">STUDENT PLANNER // {new Intl.DateTimeFormat(undefined, { weekday: "long", month: "long", day: "numeric" }).format(new Date()).toUpperCase()}</p><h1>Hello, <span>{user.name.split(" ")[0]}.</span></h1><p>Clear the queue. Keep your momentum.</p></div><button className="primary-action compact" onClick={() => { setTab("personal"); setShowComposer(true); }}><Plus size={16} /> Personal task</button></section><section className="student-stats"><article className="student-stat clipped-card"><CheckCircle2 size={20} /><strong>{assignedStats.complete}</strong><span>completed</span></article><article className="student-stat clipped-card"><Clock3 size={20} /><strong>{assignedStats.open}</strong><span>in the queue</span></article><article className={`student-stat clipped-card ${assignedStats.overdue ? "alert" : ""}`}><CalendarDays size={20} /><strong>{assignedStats.overdue}</strong><span>overdue</span></article></section><div className="planner-tabs" role="tablist"><button className={tab === "assigned" ? "active" : ""} onClick={() => setTab("assigned")}><ClipboardCheck size={16} /> Assigned <span>{assigned.length}</span></button><button className={tab === "personal" ? "active" : ""} onClick={() => setTab("personal")}><UserRound size={16} /> Personal <span>{personal.length}</span></button><button className={tab === "calendar" ? "active" : ""} onClick={() => setTab("calendar")}><CalendarDays size={16} /> Calendar</button><button className={tab === "settings" ? "active" : ""} onClick={() => setTab("settings")}><Settings2 size={16} /> Settings</button></div>
  {(tab === "assigned" || tab === "personal") && <div className="sort-control"><ListFilter size={14} /> <span>Sort</span><button className={sortBy === "due" ? "active" : ""} onClick={() => setSortBy("due")}>Due date</button><button className={sortBy === "priority" ? "active" : ""} onClick={() => setSortBy("priority")}>Priority</button></div>}
  {tab === "assigned" && <><section className="task-panel"><div className="panel-heading"><div><span className="eyebrow">FROM YOUR STAFF</span><h2>Assignment queue</h2></div></div>{assignedLoading ? <div className="empty-state">Loading your work queue…</div> : !assigned.length ? <div className="empty-state"><ClipboardCheck size={28} /><strong>Clear signal</strong><p>No staff assignments are waiting right now.</p></div> : <div className="student-task-list">{sortedAssigned.map(item => <TaskCard key={item.id} item={item} onToggle={() => setAssignedStatus.mutate({ assignmentId: item.id, done: !item.done })} />)}</div>}</section>{preferences && <PomodoroPanel settings={preferences} assignments={assigned} onSaveSettings={async next => { await updatePreferences.mutateAsync({ ...preferenceDraft, ...next }); }} />}</>}
  {tab === "personal" && <section className="task-panel"><div className="panel-heading"><div><span className="eyebrow">ONLY VISIBLE TO YOU</span><h2>Personal queue</h2></div><button className="quiet-action" onClick={() => setShowComposer(value => !value)}>{showComposer ? <><X size={15} /> Close</> : <><Plus size={15} /> Add task</>}</button></div>{showComposer && <form className="personal-composer" onSubmit={savePersonal}><div className="form-grid"><label>Subject / area<input required value={draft.subject} onChange={event => setDraft({ ...draft, subject: event.target.value })} placeholder="e.g. Study" /></label><label>Due date<input required type="date" value={draft.dueDate} onChange={event => setDraft({ ...draft, dueDate: event.target.value })} /></label></div><label>Task<input required value={draft.title} onChange={event => setDraft({ ...draft, title: event.target.value })} placeholder="What do you need to do?" /></label><label>Notes<textarea rows={2} value={draft.description} onChange={event => setDraft({ ...draft, description: event.target.value })} placeholder="Optional notes for yourself" /></label><PriorityPicker value={draft.priority} onChange={priority => setDraft({ ...draft, priority })} /><div className="composer-actions"><button type="button" className="secondary-action" onClick={closeComposer}>Cancel</button><button className="primary-action compact">{editingId ? "Save task" : "Add to queue"}</button></div></form>}{!personal.length && !showComposer ? <div className="empty-state"><Plus size={28} /><strong>Your private space is ready</strong><p>Add a personal task to keep non-class work in the same flow.</p><button className="quiet-action" onClick={() => setShowComposer(true)}>Add personal task</button></div> : <div className="student-task-list">{sortedPersonal.map(item => <TaskCard key={item.id} item={item} personal onToggle={() => setPersonalStatus.mutate({ id: item.id, done: !item.done })} onEdit={() => editPersonal(item)} onDelete={() => { if (confirm(`Delete “${item.title}”?`)) deletePersonal.mutate({ id: item.id }); }} />)}</div>}</section>}
  {tab === "calendar" && <CalendarBoard caption="YOUR DUE SIGNALS" items={calendarItems} />}
  {tab === "settings" && <section className="panel-card clipped-card settings-panel"><div className="panel-heading"><div><span className="eyebrow">PERSONAL CONTROL</span><h2>Reminders and focus</h2></div></div><div className="settings-grid"><label className="setting-toggle"><input type="checkbox" checked={preferenceDraft.reminderOptIn} onChange={event => setPreferenceDraft({ ...preferenceDraft, reminderOptIn: event.target.checked })} /><span><strong>Email deadline reminders</strong><small>Receive one upcoming and one overdue notice when enabled.</small></span></label><label>Reminder lead time<select value={preferenceDraft.reminderLeadHours} onChange={event => setPreferenceDraft({ ...preferenceDraft, reminderLeadHours: Number(event.target.value) })}><option value={1}>1 hour</option><option value={6}>6 hours</option><option value={24}>24 hours</option><option value={48}>48 hours</option><option value={72}>3 days</option></select></label><label>Focus cycle minutes<input type="number" min="1" max="120" value={preferenceDraft.focusMinutes} onChange={event => setPreferenceDraft({ ...preferenceDraft, focusMinutes: Number(event.target.value) })} /></label><label>Short break minutes<input type="number" min="1" max="60" value={preferenceDraft.shortBreakMinutes} onChange={event => setPreferenceDraft({ ...preferenceDraft, shortBreakMinutes: Number(event.target.value) })} /></label><label>Long break minutes<input type="number" min="1" max="120" value={preferenceDraft.longBreakMinutes} onChange={event => setPreferenceDraft({ ...preferenceDraft, longBreakMinutes: Number(event.target.value) })} /></label></div><button className="primary-action compact" onClick={savePreferences} disabled={updatePreferences.isPending}>Save personal settings</button></section>}
  </main></div>;
}

function PriorityPicker({ value, onChange }: { value: Priority; onChange: (value: Priority) => void }) { return <fieldset className="priority-picker"><legend>Priority signal</legend>{(["low", "medium", "high"] as Priority[]).map(priority => <button type="button" className={value === priority ? `selected ${priority}` : priority} onClick={() => onChange(priority)} key={priority}><i className={`priority-dot ${priority}`} />{priority}</button>)}</fieldset>; }

function TaskCard({ item, personal = false, onToggle, onEdit, onDelete }: { item: { id: number; subject: string; title: string; description: string | null; dueDate: Date; done: boolean; priority: Priority }; personal?: boolean; onToggle: () => void; onEdit?: () => void; onDelete?: () => void }) { const state = dueState(new Date(item.dueDate), item.done); return <article className={`student-task ${state} priority-${item.priority} ${item.done ? "is-done" : ""}`}><button className="task-toggle" onClick={onToggle} aria-label={item.done ? "Mark incomplete" : "Mark complete"}>{item.done ? <CheckCircle2 size={22} /> : <Circle size={22} />}</button><div className="task-content"><span className="subject-chip"><i className={`priority-dot ${item.priority}`} />{item.subject}</span><h3>{item.title}</h3>{item.description && <p>{item.description}</p>}<div className="task-meta"><span className={`date-stamp ${state}`}>{item.done ? "COMPLETE" : dueText(new Date(item.dueDate))}</span><span className={`priority-badge ${item.priority}`}>{item.priority}</span>{personal && <span className="private-tag">PRIVATE</span>}</div></div>{personal && <div className="task-actions"><button onClick={onEdit} aria-label="Edit personal task">Edit</button><button onClick={onDelete} className="danger-button" aria-label="Delete personal task"><Trash2 size={15} /></button></div>}</article>; }
