import { Download, ShieldAlert, Timer, TrendingUp } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { trpc } from "@/lib/trpc";

const priorityColor = { low: "#66e0ff", medium: "#ffb648", high: "#c74fe0" };
const trendColors = ["#66e0ff", "#c74fe0", "#ffb648", "#72ffcf", "#ff4d5e"];

export function StaffAnalyticsPanel() {
  const { data, isLoading } = trpc.staff.analytics.useQuery(undefined);
  if (isLoading) return <section className="panel-card clipped-card"><div className="empty-state">Computing classroom signals…</div></section>;
  const atRisk = data?.students.filter(student => student.atRisk) ?? [];
  const completionIntervals = data?.assignments.flatMap(assignment => assignment.averageDaysToComplete === null ? [] : [assignment.averageDaysToComplete]) ?? [];
  const averageCompletionDays = completionIntervals.length ? completionIntervals.reduce((sum, days) => sum + days, 0) / completionIntervals.length : null;
  const exportCsv = () => {
    if (!data) return;
    const rows = [["Student", "Email", "Assigned", "Completed", "Completion rate", "Overdue", "Focus minutes", "At risk"], ...data.students.map(student => [student.name, student.email ?? "", student.totalAssignments, student.completedAssignments, `${student.completionRate}%`, student.overdueAssignments, student.focusMinutes, student.atRisk ? "Yes" : "No"])];
    const blob = new Blob([rows.map(row => row.map(value => `"${String(value).replaceAll('"', '""')}"`).join(",")).join("\n")], { type: "text/csv" });
    const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "neon-classroom-analytics.csv"; link.click(); URL.revokeObjectURL(link.href);
  };
  return <section className="analytics-stack"><div className="analytics-summary"><article className="metric-card clipped-card"><span>CLASS FOCUS TIME</span><strong>{Math.round((data?.focusMinutes ?? 0) / 60)}<small>h</small></strong><p>Logged across enrolled students</p></article><article className="metric-card clipped-card"><span>AVG. COMPLETION TIME</span><strong>{averageCompletionDays === null ? "—" : averageCompletionDays.toFixed(1)}<small>{averageCompletionDays === null ? "" : "d"}</small></strong><p>From issue to completed state</p></article><article className="metric-card clipped-card"><span>AT-RISK SIGNALS</span><strong>{atRisk.length}</strong><p>Students with 3+ incomplete overdue items</p></article><article className="metric-card clipped-card"><span>ACTIVE TRACKING</span><strong>{data?.assignments.length ?? 0}</strong><p>Assignments in the analytics feed</p></article></div>
    <div className="analytics-grid"><article className="panel-card clipped-card analytics-chart"><div className="panel-heading"><div><span className="eyebrow">ASSIGNMENT HEALTH</span><h2>Completion by assignment</h2></div><TrendingUp size={18} /></div>{data?.assignments.length ? <ResponsiveContainer width="100%" height={250}><BarChart data={data.assignments}><CartesianGrid vertical={false} stroke="rgba(132,148,175,.16)" /><XAxis dataKey="title" hide /><YAxis domain={[0, 100]} stroke="#8b94a9" tick={{ fill: "#8b94a9", fontSize: 10 }} unit="%" /><Tooltip contentStyle={{ background: "#12151f", border: "1px solid rgba(102,224,255,.35)", color: "#eef8ff" }} formatter={(value: number) => [`${value}%`, "Completion"]} labelFormatter={(_, values) => values[0]?.payload?.title ?? "Assignment"} /><Bar dataKey="completionRate" radius={[2, 2, 0, 0]}>{data.assignments.map(item => <Cell key={item.id} fill={priorityColor[item.priority]} />)}</Bar></BarChart></ResponsiveContainer> : <div className="empty-state">Assignment data appears here after work is issued.</div>}</article>
      <article className="panel-card clipped-card analytics-chart"><div className="panel-heading"><div><span className="eyebrow">LEARNER MOMENTUM</span><h2>Completion by student</h2></div><button className="quiet-action" onClick={exportCsv}><Download size={15} /> CSV</button></div>{data?.students.length ? <ResponsiveContainer width="100%" height={250}><BarChart data={data.students} layout="vertical" margin={{ left: 10 }}><CartesianGrid horizontal={false} stroke="rgba(132,148,175,.16)" /><XAxis type="number" domain={[0, 100]} stroke="#8b94a9" tick={{ fill: "#8b94a9", fontSize: 10 }} unit="%" /><YAxis type="category" dataKey="name" width={90} stroke="#8b94a9" tick={{ fill: "#cdd9e6", fontSize: 10 }} /><Tooltip contentStyle={{ background: "#12151f", border: "1px solid rgba(102,224,255,.35)", color: "#eef8ff" }} formatter={(value: number) => [`${value}%`, "Completion"]} /><Bar dataKey="completionRate" fill="#66e0ff" radius={[0, 2, 2, 0]} /></BarChart></ResponsiveContainer> : <div className="empty-state">Learner analytics will appear once students are enrolled.</div>}</article></div>
    <article className="panel-card clipped-card analytics-trend"><div className="panel-heading"><div><span className="eyebrow">COMPLETION HISTORY</span><h2>Cumulative student completion trend</h2></div></div>{data?.completionTrend.length && data.trendSeries.length ? <ResponsiveContainer width="100%" height={260}><LineChart data={data.completionTrend}><CartesianGrid stroke="rgba(132,148,175,.16)" /><XAxis dataKey="date" stroke="#8b94a9" tick={{ fill: "#8b94a9", fontSize: 10 }} /><YAxis allowDecimals={false} stroke="#8b94a9" tick={{ fill: "#8b94a9", fontSize: 10 }} /><Tooltip contentStyle={{ background: "#12151f", border: "1px solid rgba(102,224,255,.35)", color: "#eef8ff" }} /><Legend wrapperStyle={{ fontSize: 10, color: "#cdd9e6" }} />{data.trendSeries.map((series, index) => <Line key={series.key} type="monotone" dataKey={series.key} name={series.name} stroke={trendColors[index % trendColors.length]} strokeWidth={2} dot={{ r: 3 }} />)}</LineChart></ResponsiveContainer> : <div className="empty-state"><TrendingUp size={23} /><strong>Completion history will appear here</strong><p>The chart activates when students mark staff assignments complete.</p></div>}</article>
    <article className="panel-card clipped-card at-risk-panel"><div className="panel-heading"><div><span className="eyebrow">INTERVENTION QUEUE</span><h2>Students trending behind</h2></div><ShieldAlert size={18} /></div>{atRisk.length ? <div className="risk-list">{atRisk.map(student => <div key={student.id}><span>{student.name.slice(0, 2).toUpperCase()}</span><p><strong>{student.name}</strong><small>{student.overdueAssignments} overdue · {student.completionRate}% complete · {student.focusMinutes} focus min</small></p></div>)}</div> : <div className="empty-state"><Timer size={23} /><strong>No intervention signals</strong><p>Students enter this queue after three incomplete overdue assignments in the current tracking data.</p></div>}</article>
  </section>;
}
